src/objects/DEN_Appointment__c.object
<CustomObject>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DEN_Appointment</relationshipLabel>
        <relationshipName>DEN_Appointment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DEN_Appointment</label>
    <nameField>
        <label>DEN_Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DEN_Appointment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DEN_ClientExtension.cls
public class DEN_ClientExtension {
    public DEN_ClientExtension(ApexPages.StandardController stdController) {
        
    }
    
    public List<Contact> getClients() {
    	//GK: jesli tak robisz to pamietaj ze przy kazdym odswiezeniu strony ten select sie wykona
        return [SELECT Id, FirstName, LastName, Name, Phone, Email FROM Contact WHERE Id IN (SELECT Patient__c FROM DEN_Appointment__c)];
    }
}