src/objects/DEN_Appointment__c.object
<CustomObject>
    <fields>
        <fullName>DateTime__c</fullName>
        <label>DateTime</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dentist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dentist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DEN_Appointment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DEN_Appointment</relationshipLabel>
        <relationshipName>DEN_Appointment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Oczekująca na potwierdzenie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zaakceptowana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Odrzucona</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>DEN_Appointment</label>
    <nameField>
        <label>DEN_Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DEN_Appointment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DEN_Config__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dentist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dentist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DEN_Config</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndingHour__c</fullName>
        <label>EndingHour</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StartingHour__c</fullName>
        <label>StartingHour</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Weekday__c</fullName>
        <label>Weekday</label>
        <picklist>
            <picklistValues>
                <fullName>MON</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TUE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>THU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FRI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>DEN_Config</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>DEN_Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DEN_Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Chirurg Szczękowy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ortodonta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stomatolog</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DEN_RegistrationController.cls
public with sharing class DEN_RegistrationController {
    private static final String ALL_DENTISTS = 'SELECT Id, Name, Type__c FROM User WHERE Type__c != null';
    private static final String FILTERED_DENTISTS = 'SELECT Id, Name, Type__c FROM User WHERE Type__c =: dentistType';
    private static final String FILTERED_DATE = 'SELECT Id, Name, Type__c FROM User WHERE Type__c != null AND Id IN :availableDentists';
    private static final String FILTERED_DENTISTS_DATE = 'SELECT Id, Name, Type__c FROM User WHERE Type__c =: dentistType AND Id IN :availableDentists';
    private static final List<DEN_Config__c> ALL_CONFIG = [SELECT Id, Name, Weekday__c, Date__c, StartingHour__c, EndingHour__c, Dentist__c FROM DEN_Config__c];
    
    private List<Id> availableDentists {get; set;}
    public String dentistType {get; set;}
    public Id dentistId {get; set;}
    public DEN_Appointment__c appointment {get; set;}
    public Contact contact {get; set;}
    
    public DEN_RegistrationController() {
        appointment = new DEN_Appointment__c();
        contact = new Contact();
    }
    
    public ApexPages.StandardSetController dentistSetCon {
        get {
			return dentistSetCon == null ? new ApexPages.StandardSetController(Database.getQueryLocator(ALL_DENTISTS)) : dentistSetCon;
        }
        set;
    }
    
    public PageReference filterTypes() {
        availableDentists = (appointment.Date__c == null ? null : getAvailableDentists(appointment.Date__c));
        dentistSetCon = new ApexPages.StandardSetController(Database.getQueryLocator(getQueryString()));
        return null;
    }
    
    public List<User> getDentists() {
        return (List<User>)dentistSetCon.getRecords();
    }
    
    public List<SelectOption> getDentistTypes() {
        List<SelectOption> result = new List<SelectOption>();
        result.add(new SelectOption('ANY', '--Any--'));
        for (Schema.PicklistEntry item : User.Type__c.getDescribe().getPicklistValues()) {
            result.add(new SelectOption(item.value, item.label));
        }
        return result;
    }
    
    private List<Id> getAvailableDentists(Date filteredDate) {
        Set<Id> availableDentists = new Set<Id>();
        String selWeekDay = DEN_DateUtil.getWeekdayFrom(filteredDate);
        if (filteredDate >= Date.today()) {
            for (DEN_Config__c config : ALL_CONFIG) {
                if ((config.Date__c != null && config.Date__c == filteredDate) ||
                    (config.Weekday__c != null && config.Weekday__c.equals(selWeekDay.toUpperCase()))) {
                        availableDentists.add(config.Dentist__c);
                    }
            }
        }
        return new List<Id>(availableDentists);
    }
    
    private String getQueryString() {
        if ('ANY'.equals(dentistType)) {
        	return appointment.Date__c == null ? ALL_DENTISTS : FILTERED_DATE;
        }
        else {
            return appointment.Date__c == null ? FILTERED_DENTISTS : FILTERED_DENTISTS_DATE;
    	}
    }
    
    public PageReference send() {
        String email = contact.Email;
        List<Contact> contactsMatched = [SELECT Id, Name, Email FROM Contact WHERE Email =: email];
        if (contactsMatched.isEmpty()) {
            insert contact;
        }
        appointment.Status__c = getDefaultStatus();
        appointment.Dentist__c = dentistId;
        appointment.Patient__c = [SELECT Id, Name, Email FROM Contact WHERE Email =: email][0].Id;
        //temp
        appointment.Date__c = Date.newInstance(2016, 07, 18);
        //temp
        appointment.DateTime__c = DateTime.newInstance(appointment.Date__c, Time.newInstance(0, 0, 0, 0));
        appointment.Name = getAppointmentName();
        insert appointment;
        return null;
    }
	
    private String getAppointmentName() {
        User dentist = [SELECT FirstName, LastName FROM User WHERE Id =: dentistId][0];
        Id ClientId = appointment.Patient__c;
        Contact client = [SELECT FirstName, LastName FROm Contact WHERE Id =: clientId][0];
        return (dentist.FirstName.left(1) + dentist.LastName.left(1) + '_' + client.FirstName.left(1) + client.LastName.left(1)).toUpperCase() + '_' +
            appointment.Date__c.year() + String.valueOf(appointment.Date__c.month()).leftPad(2).replace(' ', '0') + String.valueOf(appointment.Date__c.day()).leftPad(2).replace(' ', '0') +
            '_' + String.valueOf(appointment.DateTime__c.hour()).leftPad(2).replace(' ', '0') + String.valueOf(appointment.DateTime__c.minute()).leftPad(2).replace(' ', '0');
    }
    
    private String getDefaultStatus() {
        for (Schema.PicklistEntry value : DEN_Appointment__c.Status__c.getDescribe().getPicklistValues()) {
            if (value.isDefaultValue()) {
                return value.getValue();
            }
        }
        return null;
    }
}