src/objects/DEN_Appointment__c.object
<CustomObject>
    <fields>
        <fullName>DateTime__c</fullName>
        <label>DateTime</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dentist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dentist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DEN_Appointment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DEN_Appointment</relationshipLabel>
        <relationshipName>DEN_Appointment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DEN_Appointment</label>
    <nameField>
        <label>DEN_Appointment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DEN_Appointment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Chirurg Szczękowy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ortodonta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stomatolog</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DEN_ClientExtensionTest.cls
@isTest
public class DEN_ClientExtensionTest {
    @isTest static void testExtension() {
        Test.setCurrentPage(Page.DEN_Client);
        Contact c = new Contact(FirstName = 'Bob', LastName = 'Klop', email = 'testContactEmail@email.pl');
        insert c;
        Profile p = [SELECT Id FROM Profile WHERE Name = 'DEN_dentist'];
        User u = new User(FirstName = 'John', lastName = 'Bob', email = 'test@test.pl', profileId = p.Id, Type__c = 'Ortodonta', Username='testDentist@fortesting.pl', Alias='johnbo', CommunityNickname='johnbo', TimeZoneSidKey='Europe/Berlin', LocaleSidKey='pl_PL', EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US');
        insert u;
        DateTime dt = DateTime.newInstance(Date.newInstance(2016, 8, 22), Time.newInstance(6, 30, 0, 0));
        insert new DEN_Appointment__c(Patient__c = [SELECT Id FROM Contact WHERE email = 'testContactEmail@email.pl'].Id, Dentist__c = [SELECT Id FROM User WHERE Username = 'testDentist@fortesting.pl'].Id, DateTime__c = dt, Date__c = dt.date());
        DEN_ClientExtension ext = new DEN_ClientExtension(new ApexPages.StandardController(new Contact()));
        system.assert(!ext.clients.isEmpty());
        system.assert(ext.clients.size() == 1);
    }
}